BOX_WIDTH = 140
BUTTON_WIDTH = 20

GEAR_SLOT = 11
GEAR_ITEM  = 15
EQUIPPABLE_NAME = 15
MIDDLE_SPACE = 14
STATS_SPACE = 3
TITLE_SPACE = 12
COLUMN_SPACE = 2
NAME_SPACE = 13
DESCRIPTION_NAME = 21
DESCRIPTION_SPACE = 21
TURN_SPACE = 5