BOX_WIDTH = 140
BUTTON_WIDTH = 20

GEAR_SLOT = 11
GEAR_ITEM  = 15
EQUIPPABLE_NAME = 15
MIDDLE_SPACE = 14
STATS_SPACE = 3
TITLE_SPACE = 12
COLUMN_SPACE = 2
NAME_SPACE = 13
DESCRIPTION_NAME = 21
DESCRIPTION_SPACE = 21
TURN_SPACE = 5

COMBAT_NAME_SPACE = 10
COMBAT_HP_RES_SPACE = 8
COMBAT_HP_RES_BAR = 8
COMBAT_HP_RES_LEN = 5

MIN_DAMAGE = 0.9
MAX_DAMAGE = 1.1