BOX_WIDTH = 140
BUTTON_WIDTH = 20
COLUMN_SPACE = 2

# Stats
STATS_NAME = 14
STATS_SPACE = 3
# Combat
COMBAT_NAME = 14
COMBAT_SPACE = 16
# Gear and Equippable
GEAR_SLOT = 11
GEAR_ITEM  = 15
EQUIPPABLE_NAME = 15

TITLE_SPACE = 12

NAME_SPACE = 12
DESCRIPTION_NAME = 21
DESCRIPTION_SPACE = 21
TURN_SPACE = 5

# Combat ui
COMBAT_NAME_SPACE = 10
COMBAT_HP_RES_SPACE = 8
COMBAT_HP_RES_BAR = 8
COMBAT_HP_RES_LEN = 5
