BOX_WIDTH = 141

BUTTON_WIDTH = 25
BUTTON_TEXT = 23
BUTTON_SPACE = 2
COLUMN_SPACE = 2

# Stats
STATS_NAME = 14
STATS_SPACE = 3
# Combat
COMBAT_NAME = 14
COMBAT_SPACE = 16
# Gear and Equippable
GEAR_SLOT = 13
GEAR_ITEM  = 16
EQUIPPABLE_NAME = 20
NAME_SPACE = 12

# Combat ui
COMBAT_NAME_SPACE = 10
COMBAT_HP_RES_SPACE = 8
COMBAT_HP_RES_BAR = 8
COMBAT_HP_RES_LEN = 5

# Buffs & Debuffs
BUFF_NAME = 30
BUFF_DESCRIPTION = 30
BUFF_EFFECT = 30
BUFF_DURATION = 10

POTION_NAME = 17
POTION_EFFECT = 17

OTHER_NAME = 12
OTHER_AMOUNT = 5

ITEM_VALUE = 5